FROM microsoft/dotnet:1.1-sdk-projectjson

COPY . /myapp
WORKDIR /myapp

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]

EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000

ENTRYPOINT ["dotnet", "run"]
