FROM microsoft/dotnet:latest

COPY . /todoapi
WORKDIR /todoapi/src

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]

EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000

ENTRYPOINT ["dotnet", "TodoApi.dll"]
