FROM microsoft/dotnet:latest

RUN mkdir -p /usr/src/todo
WORKDIR /usr/src/todo

COPY . /usr/src/todo

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]

EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000

ENTRYPOINT ["dotnet", "run"]
